### ISSUE TITLE
Research Cloudinary and API calls

### ISSUE THREAD

**Issue by AdamKassem** [acm-projects/Time-Capsule#5]
- [documentation](https://cloudinary.com/documentation/how_to_integrate_cloudinary)
- [tutorials](https://cloudinary.com/documentation/tutorial_screencasts)

**Comment by VictoriaDeLozier** [comment]
Hi Adham! I started researching Cloudinary and making API calls today, and I'm a bit confused as to what specifically you would like me to research, so up until now I've gained a basic understanding of both. Could you elaborate on which direction you'd like me to take and what information the group needs?
